apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: fastapi-multi
spec:
  containers:
    - name: fastapi-app
      image: bayardozelaya/vibradev:latest
      ports:
        - containerPort: 5000
      env:
        - name: GREETING
          value: "Hello from FastAPI in a multi-container pod!"
      # Mount a volume from a ConfigMap (see next section)
      volumeMounts:
        - name: config-volume
          mountPath: /app/config
    - name: sidecar-logger
      image: busybox
      command:
        [
          "sh",
          "-c",
          'while true; do echo "Sidecar is logging at $(date)"; sleep 10; done',
        ]
  volumes:
    - name: config-volume
      configMap:
        name: greeting-config
  imagePullSecrets:
    - name: regcred
