apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: app-space
  labels:
    app: fastapi-multi
spec:
  containers:
    - name: fastapi-app
      image: my-fastapi-app:latest
      ports:
        - containerPort: 5000
      env:
        - name: GREETING
          value: "Hello from FastAPI in a multi-container pod!"
      # Mount a volume from a ConfigMap (see next section)
      volumeMounts:
        - name: config-volume
          mountPath: /app/config
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
    - name: sidecar-logger
      image: busybox
      command:
        [
          "sh",
          "-c",
          'while true; do echo "Sidecar is logging at $(date)"; sleep 10; done',
        ]
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
  volumes:
    - name: config-volume
      configMap:
        name: greeting-config
  imagePullSecrets:
    - name: regcred
